name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a7ced34c943c47bb84618d901d4fa6664e8014c1a028fd0024da7ee07c6bc46"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
