name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5655a79faaf111bdd6c6ed8006ced657d6c7cd8a97389db8f472746964f0e14"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
