name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9237587790d703cd600f603c5a19e10dbbee6265d053f01664a04a72d641842a"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
