name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8cbc4bf72653f3fc5abba0020374735cc5ab6a326b7f29c4b976ff4f506c65d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
