name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49df58e35fd56d3a083e3e0cf8f397bb28e5dc08a1f8e0bf9df4767cd12dc0fe"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
