name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd126acc23f31ad9a902f6ffe46cc528ab4c7ebe0096f55f0223da58c593e85"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
