name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90c3bfce437668b7a1f41fba6088f2eea745752f3fce387b67e747f0a48630b4"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
