name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec012e4f6dd79a4382a8863eabdb1ec31a4037cddc6316e5cf7a69b9549a3850"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
