name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e83409b609400612a5bf2cc83718921b99c8ea398e33a2db4a97eccdd79be4ac"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
