name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f3d65d4d7b136ce62b650630d05dd3fe32f4cd993c99bc970938fc82a042bb5"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
