name = "HexMC"
author = "Tabzlock"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a692d484008aefa3d9eb9ae10fb15155256880c7a27ca036f71f487fc68b0ef7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
