name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe43222af1219667d400a43ba10574f18f828d29aab89d78ac1bef90999fa4d6"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
