name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5491be60e6b926806b509b3a8e515b0ac6aea4b905cf8b4fb3978691fee064e8"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
