name = "HexMC"
author = "Tabzlock"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d55a43797660b4b99f816dad75d631da0e49f754da4c47123c79cf07d70568a"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
