name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cacbeb3935fb2f3b6f4e60c1d51d5782b39a5e70c8c6e670d3cc4008dc3da30"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
