name = "HexMC"
author = "Tabzlock"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec6a09faa40d0e8839ed2ed925d0d3ba3d05ce414342c8e7c91ea3e7f2fecb83"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
