name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7106cf430924af9bc9ec30d3fbc577870e1df5eeb25abd287a5727037a6988a"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
