name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7241dc70de2af19d672ea0247ffe58672e95da6bd8ecf11a3ad68252b20de4bc"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
