name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bbb9f42e4a8ab950fba469399dce083659029f29aab530e20f873cbef5f159b"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
