name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "333d90f46ee78a2e9f7433c542ffbcc78627aea22b60875a18eb2fd13e480624"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
