name = "HexMC"
author = "Tabzlock"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c5818e057d242c283b132ced59e14efa524145cca978cef4c0e80e69fa5d6e4"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
