name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5224e943204d4a4378d9a2784acb38fe5aeb5aa8e2b63c65079ce3c905f0e0fd"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
