name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53e4809513e2f603da3f3969feb8d030dfedbc21b12705bc9194199dfa6462e2"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
