name = "HexMC"
author = "Tabzlock"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0f2ce12b4a76c28344bd5b4c32a0a80a31e589a24522406422c43748e25fe49"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
